[package]
authors = [
  "Emil Ernerfeldt <emil.ernerfeldt@gmail.com>",
  "rerun.io <opensource@rerun.io>",
]
categories = ["gui"]
description = "A tiling layout engine for egui with drag-and-drop and resizing"
edition = "2021"
homepage = "https://github.com/rerun-io/egui_tiles"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]
keywords = ["egui", "gui", "tile", "dock", "layout"]
license = "MIT OR Apache-2.0"
name = "egui_tiles"
readme = "README.md"
repository = "https://github.com/rerun-io/egui_tiles"
rust-version = "1.69"
version = "0.1.0"

[package.metadata.docs.rs]
all-features = true


[dependencies]
ahash = "0.8"
egui = { version = "0.22", default-features = false }
itertools = "0.11"
log = { version = "0.4", features = ["std"] }
serde = { version = "1", features = ["derive"] }


# For the example:
[dev-dependencies]
eframe = { version = "0.22", default-features = false, features = [
  "default_fonts",
  "glow",
  "persistence",
] }
env_logger = "0.10"
